### ISSUE TITLE
Where is the hamming diversity?

### ISSUE THREAD

**Issue by xuanchien** [ashwinkalyan/dbs#1]
Hi Ashwin,

I don't quite understand your code to add diversity to the probability. In your paper, you multiplied `lambda` with the Hamming diversity. But in your code, you only minus `lambda` from the probability. 

Can you provide your explanation in greater detail?

Thanks

**Comment by ashwinkalyan** [comment]
Hi, Check the `add_diversity`   [https://github.com/ashwinkalyan/dbs/blob/master/dbs/beam_utils.lua#L177](url) method. The hamming diversity is calculated by keeping a count of the occurence of a token in previous time steps / groups. 
I hope this helps! 
Thanks for the interest!
